# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfc7c5af59cfa43604dfddb0f803b2e944800b3a451d25646519746618d4b1c8fdb505daaeb7356b0fb82f28b32e93d379c81a004538153af4833d8bc13c2f89

test:
  secret_key_base: cf1bdf048aef7120fb6260872bcd7b6d9c168a8a9177cc1fdc4168ecb5278e918b5a786dc2898a37fb01b358685f3ec4ef5c5cf964859ed51dfa640fb72ada6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
